// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "tJEWHAayjDedT4aFL6lIIvzxGbO0HsJywsOgEuocVw64ftGYRK6C3N2gxjD0VovaKAbt5c";
}
}
}

